- name: Get bahmniapps from remote location if configured
  get_url: url={{ bahmniapps_url }}
   force=yes
   dest=/opt/bahmni-web/etc/bahmniapps.zip
   mode=0755
  when: bahmniapps_url is defined

- name: unlinking /var/www/bahmniapps
  command: unlink /var/www/bahmniapps
  when: bahmniapps_url is defined

- name: Removing amman-bahmniapps folder
  command: rm -rf /opt/bahmni-web/etc/amman-bahmniapps
  when: bahmniapps_url is defined

- name: Unzip downloaded bahmniapps file
  command: unzip /opt/bahmni-web/etc/bahmniapps.zip -d /opt/bahmni-web/etc/amman-bahmniapps
  when: bahmniapps_url is defined

- name: linking /var/www/bahmniapps to amman-release-84 bahmniapps
  command: ln -s /opt/bahmni-web/etc/amman-bahmniapps /var/www/bahmniapps
  when: bahmniapps_url is defined
