- name: Uninstall bahmni-batch for amman exports
  yum:
    name: bahmni-amman-batch
    state: absent
  when: bahmni_amman_batch_url is defined

- name: Install bahmni-batch for amman exports
  yum:
    name: "{{ bahmni_amman_batch_url }}"
  when: bahmni_amman_batch_url is defined

- name: Create a crontab to sync amman-exports directory on primary
  cron:
    name: "sync_amman_exports_cron"
    minute: 59
    hour: 23
    user: "root"
    job: "rsync -rh --progress -i --itemize-changes --update --rsync-path='sudo rsync' -pog {{amman_exports_dir}} -e 'ssh -o StrictHostKeyChecking=no' {{bahmni_support_user}}@{{item}}:{{amman_exports_dir}}/../"
  when: "{{ (passive is not defined or passive != 'yes') }}"
  with_items: "{{groups['bahmni-emr']}}"

- name: Removing the bahmni-batch cron on secondary
  shell: crontab -l -ubahmni | grep -v bahmni-batch  | crontab -ubahmni -;
  when: "{{ (passive is defined and passive == 'yes') }}"
  with_items: "{{groups['bahmni-emr']}}"
